package cloud.autotests.tests;

import cloud.autotests.helpers.DriverUtils;
import io.qameta.allure.Description;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static com.codeborne.selenide.Selenide.open;
import static com.codeborne.selenide.Selenide.title;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;


public class GeneratedTests extends TestBase {
    @Test
    @Description("Soon to be implemented by you (or QA.GURU engineers)")
    @DisplayName("Infinnity_Solutions_mainpagetest")
    void generatedTest() {
        step("https://www.infinnity.ru/", () -> {
            step("// todo: just add selenium action");
        });

        step("click on the language switch button", () -> {
            step("// todo: just add selenium action");
        });

        step("Check that two languages are available", () -> {
            step("// todo: just add selenium action");
        });

        step("Select English", () -> {
            step("// todo: just add selenium action");
        });

        step("Check that the \"PRODUCTS AND SERVICES\" button is visible on the page", () -> {
            step("// todo: just add selenium action");
        });

        step("click on the button \"PRODUCTS AND SERVICES\"", () -> {
            step("// todo: just add selenium action");
        });

        step("Enter in the name field \"David\"", () -> {
            step("// todo: just add selenium action");
        });

        step("Enter the phone number 89503473792 in the field", () -> {
            step("// todo: just add selenium action");
        });

        step("enter email kuznetsov.david@gmail.com in the field", () -> {
            step("// todo: just add selenium action");
        });

        step("Enter valid text in the Type your enquiry here field", () -> {
            step("// todo: just add selenium action");
        });

        step("Press send button", () -> {
            step("// todo: just add selenium action");
        });

        step("Check if the message has been sent", () -> {
            step("// todo: just add selenium action");
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page title should have header text")
    void titleTest() {
        step("Open url 'https://www.infinnity.ru/'", () ->
            open("https://www.infinnity.ru/"));

        step("Page title should have text 'Infinnity Solutions - ideas and technologies'", () -> {
            String expectedTitle = "Infinnity Solutions - ideas and technologies";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page console log should not have errors")
    void consoleShouldNotHaveErrorsTest() {
        step("Open url 'https://www.infinnity.ru/'", () ->
            open("https://www.infinnity.ru/"));

        step("Console logs should not contain text 'SEVERE'", () -> {
            String consoleLogs = DriverUtils.getConsoleLogs();
            String errorText = "SEVERE";

            assertThat(consoleLogs).doesNotContain(errorText);
        });
    }
}